# Generated by Django 5.2.8 on 2025-11-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('SALARY', 'Salary'), ('FD', 'Fixed Deposit')], default='SAVINGS', max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('ifsc_code', models.CharField(default='SFC00020911', max_length=11)),
                ('branch_name', models.CharField(default='Main Branch', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.URLField(default='Empty')),
            ],
        ),
    ]
